stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git rsync
    - git config --global user.name "LifeVerse-Development"
    - git config --global user.email "lifeversegame@gmail.com"
    - git init
    - git remote remove origin || true
    - git remote add origin https://oauth2:${GITHUB_TOKEN}@github.com/LifeVerse-Development/Discord-Bot.git
    - git fetch origin main || git checkout -B main
  script:
    - echo "Deploying to GitHub..."
    - rsync -av --exclude='.git' ./ ./
    - git add .
    - git commit -m "Automated deployment from GitLab CI/CD"
    - git push origin main
  only:
    - main