stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git rsync openssh
    - git config --global user.name "LifeVerse-Game"
    - git config --global user.email "lifeversegame@gmail.com"
    - mkdir -p ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - echo "$CI_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - echo "Deploying to GitHub..."
    - git clone git@github.com:LifeVerse-Game/Discord-Bot.git target-repo
    - rsync -av --exclude='.git' ./ target-repo/
    - cd target-repo
    - git add .
    - git commit -m "Automated deployment from GitLab CI/CD" || echo "No changes to commit"
    - git push origin main
  only:
    - main
